"""alerts

Revision ID: d467b8de4c83
Revises: f86c7aa7045d
Create Date: 2026-08-30 14:47:11.540613
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d467b8de4c83"
down_revision: str | None = "f86c7aa7045d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_alert_id", sa.String(length=200), nullable=False),
        sa.Column("source_system", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("customer_ref", sa.String(length=200), nullable=True),
        sa.Column("account_ref", sa.String(length=200), nullable=True),
        sa.Column("counterparty_ref", sa.String(length=200), nullable=True),
        sa.Column("merchant_name", sa.String(length=255), nullable=True),
        sa.Column("merchant_name_normalised", sa.String(length=255), nullable=True),
        sa.Column("mcc", sa.String(length=8), nullable=True),
        sa.Column("device_id", sa.String(length=200), nullable=True),
        sa.Column("session_id", sa.String(length=200), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column(
            "rule_codes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "typologies",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "raw_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("ground_truth_group_id", sa.String(length=200), nullable=True),
        # FK to cases.id added by a later migration (cases table does not exist yet)
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("source_system", "external_alert_id", name="uq_alerts_source_external"),
    )
    op.create_index(
        "ix_alerts_customer_ref_event_time", "alerts", ["customer_ref", "event_time"], unique=False
    )
    op.create_index("ix_alerts_device_id", "alerts", ["device_id"], unique=False)
    op.create_index("ix_alerts_event_time", "alerts", ["event_time"], unique=False)
    op.create_index("ix_alerts_ip_address", "alerts", ["ip_address"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_alerts_ip_address", table_name="alerts")
    op.drop_index("ix_alerts_event_time", table_name="alerts")
    op.drop_index("ix_alerts_device_id", table_name="alerts")
    op.drop_index("ix_alerts_customer_ref_event_time", table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
