"""audit_grants

Revision ID: de0fe5693ed3
Revises: 327e48bef586
Create Date: 2026-08-30 22:06:32.084030
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de0fe5693ed3"
down_revision: str | None = "327e48bef586"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Hand-written (not autogenerated): Alembic does not model role grants. This
# migration is what turns ``app_user`` from "USAGE on schema public only" (set up
# by the bootstrap / deployment role script) into the least-privilege *runtime*
# role the application actually connects as.
#
# The load-bearing invariant: ``app_user`` can INSERT into ``audit_events`` (the
# audit write path needs it) but can NEVER UPDATE or DELETE a row there -- the
# audit log is append-only at the database-privilege level, not merely by
# convention. ``audit_streams`` keeps UPDATE (``record_audit`` bumps
# ``last_seq`` / ``last_hash`` under ``SELECT ... FOR UPDATE``) but loses DELETE.
#
# Everything else in ``public`` gets full CRUD: the case, grouping and
# assignment tables legitimately update and delete non-audit rows.


def upgrade() -> None:
    # Full CRUD on every existing table, then carve out the audit exceptions.
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user")
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user")
    op.execute("REVOKE UPDATE, DELETE ON audit_events FROM app_user")
    # app_user needs UPDATE on audit_streams (last_seq / last_hash tip bump); it
    # must not be able to DELETE a stream tip.
    op.execute("REVOKE DELETE ON audit_streams FROM app_user")
    # Same shape for tables created by future migrations (they run as this same
    # owner role, so the default privileges attach to them automatically).
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user"
    )
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app_user"
    )


def downgrade() -> None:
    # Undo the default-privilege rules first so they stop attaching to new
    # objects, then strip every table/sequence privilege back to the
    # pre-migration state (schema USAGE + database CONNECT, granted by the
    # bootstrap script, are left intact).
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        "REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM app_user"
    )
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE, SELECT ON SEQUENCES FROM app_user"
    )
    op.execute("REVOKE ALL ON ALL TABLES IN SCHEMA public FROM app_user")
    op.execute("REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM app_user")
    # Keep the baseline the bootstrap established.
    op.execute("GRANT USAGE ON SCHEMA public TO app_user")
